{% set name = "web.py" %}
{% set version = "0.62" %}
{% set sha256 = "5ce684caa240654cae5950da8b4b7bc178812031e08f990518d072bd44ab525e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - web

about:
  home: http://webpy.org
  license: Public domain
  summary: web.py is a web framework for Python that is as simple as it is powerful.
  dev_url: https://github.com/webpy/webpy

extra:
  recipe-maintainers:
    - sebastian-luna-valero
