{% set name = "web.py" %}
{% set version = "0.40" %}
{% set sha256 = "dc5e42ffbc42d77d07f75b7acca9975a3368ae609774e49ddebb497a784131f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - web

about:
  home: http://webpy.org
  license: Public domain
  summary: 'web.py is a web framework for Python that is as simple as it is powerful.'
  dev_url: https://github.com/webpy/webpy

extra:
  recipe-maintainers:
    - sebastian-luna-valero
