travis:
  secure:
    BINSTAR_TOKEN: Ypo7RPf5UFmPSP6tgeyQm9chH4TxsDSHQ1vZicj1NkgLNwJbQ8xPKxkJyrNM+IvG2e2hlaErhh4RBcOnvD/6Xw84aCkTZIMscWRWAjSJC8xiOuO8xXjBbOQbai98v125STDLoLNnpKx7rAu30h0699Fk7K67BAoos7Cs+SMTVV/YKxVJqYGtB1xRfb5aEsVBz1jaaEZduiQFz3z/GrAp2HQWyaxPMjWdrLhGpsD5Uf8bPOWDI9947Ug826CIRkDfRu892xStebaORP1J42BolSqV59I096K0LaPQ2gKe0hLIGRN+HatGxg7xkf6plKx/SVerlqUpZTGsvf3rhRoQ7BrnLTryuPMx3Rle8LC5ErV/W2AY+5nlKc3y8xD6idRDr+wVNKrpuwH3D5kwQLw9xUHsNcAGDk/mMuEtZ1k4bRQRhxUCK6ZCISc118fDV8zMACItvpKYZutO32mL4u3hgpclFL02Mxcd3trzIuodiyY0oz4Xzp3I9vp5cGYgCH+x1yfpZ/MAH+zAVhlWSnzTbsTD5jTZS3eJWozd3LK+vvbXsdFpc/7zspMyW3Yj5UZLhP5GM23yLqgnPIzcQZuYdEiRtHVGlcz+aIBr3aHKhx1W1yFOcJ0ZyOU+XdfJ+U+eoLB/B/63Qm/dX4JA+aRcaTmX5dvlWkhwNNEPxwd9pqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
