travis:
  secure:
    BINSTAR_TOKEN: UUjbB5d842/eUnRM7CSJwLmW1dtIfq7SeKPzZoekB3w3hYg59na9egtU+Ebaz7V6CGc5yFWJtz/oAU7yzdz7bXnzRYoddQEaltHewDyYmk0wiTiNvq/LDI8q0N11S0/CYZmyX8PthB6WtNPnhTcccbeUDff8N4SIpPf4Mi0xyvt3Mqr/iRUNbibXn9Kezqu8JgeXqwfW/3n4Ku/jFslglKKlkI46TnpEXa9UIPZM9JDDrsB8gKdiBrGbV00aP361x9gR0lsM5wuVBHLONhpzcg35hCFnc2ZPU01BboOc5D9obX3dgNDAZaL0mLEjKW+bf+VFTi7YB0gIf8ud0oRO7ueIFbYP8FhYBKKRuyVrzovxVeeTmYpJFVkXRaRspv0BVWy7nKoXu5BjzMBom/YmYtygf3DxAImpwWdDBwl5oRD/3UquokkgJqqOOHukpQ4+OdYoeo3/VLkhNorCi9Lu1UgWdNQVSRZO4SUD1amsp9cB5K1WD0521AcY38Z9Vs0OE+BqF0rcMHEkznuS3pkVb+OPSWGSaBs0+HyBU8JFBzfbrIkYbUiTe8RuCdbGpUmcZtiWenUoWuEXotLDxE6f60kTWOl2ddxfTLFOLsRBqSeggPwGld0zoeGZXFkzU6wZ/Hz3kj7UQPPdeZfGTIMoQbP9Gst++4/QiF6tny94zXw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
