travis:
  secure:
    BINSTAR_TOKEN: JVyWk+cyE6Jn+N9s+76iW6RC0vkU5SsFTOGDsub4x3EMqft+21AJMAfB/aW50qyGMkbNqBbkVPzOSSVvm+Qexu/0LXmwfOzSBuf9KR7kw639yP2m/GtxqjDw1Q/gmtSL1OMVx1w7BRURkwmrme+MnZLBgg/onHY6m67I7nYIz9y4xmWd5gMuVl7llL6BuXg9E/nj4TujQ8OyKU6t7q1K8eTLM6CSmpRCJidGjPuFMDOpgeut7j5huulaSYpdSGJi7MZ+zPaq0r0h26lh4Ro9dkAUF8Asl4NqvstLveL/cq7LXei+LVjk0JbFbxuSJmsFjCA0yBdXC3HtzcoYVsrIzYPLWEoANE7oPNGQfJCB3ICkm3QMR2pC4JhcKDcDGXzNejQ0u69Iy5ze7GjMUt6UVp3h1bS1XlpuNTxZjq36ARDk5Bl5ZuweTmoiVytdTZnzPalpiIttu0lDM3/xWfxJxWmm6OmZ2GL/QONbjEOvBfwIk1vTkYml0+WpEyBPos4CxBS2WB0g+FUGe9xv0Uw8mtMsmW3u0KG6nFqQNPZJxSoq3+kEdJnlh2IT8s3lRYLworc+vixMHVLyrEcEvZFGJHk1njI7nAkQ+cr9qyM2OAxuHIs/b4A/ECl6alEQW9ulhZMEoyTf+ZJrl8diRbMKopW5vq3a/bHkkB4F9Ko6/hk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
